language: node_js
node_js:
  - 4.1
install:
  - npm install -g grunt-cli
  - npm install grunt
  - npm install grunt-contrib-clean
  - npm install grunt-contrib-copy
  - npm install grunt-contrib-jshint
  - npm install grunt-contrib-nodeunit
  - npm install grunt-contrib-uglify
  - npm install moment

notifications:
  slack:
    rooms:
      - nest-parrot:z3jqw9krJbPu0CcQBKS90AnZ#travis-ci

deploy:
    skip_cleanup: true
    provider: npm
    email: bradwoo8621@gmail.com
    api_key: 3cae1ae6-4d60-433d-b4d8-1072f9a7c4c1
    on:
        tags: true
